import { Ability } from "./Ability";
import { Asset } from "./Asset";
import { Biography } from "./Biography";
import { Condition } from "./Condition";
import { Equipment } from "./Equipment";
import { Flaw } from "./Flaw";
import { GrowthRate } from "./Growthrate";
import { Inventory } from "./Inventory";
import { LevelUp } from "./LevelUp";
import { PersonalAbility } from "./PersonalAbility";
import { Skill } from "./Skill";
import { Stats } from "./Stats";
import { Support } from "./Support";
import { Terrain } from "./Terrain";
import { UnitClass } from "./UnitClass";
import { Weapon } from "./Weapon";

export class Character {
    id: string;
    biography: Biography;
    currentHP: number;
    personalAbility: PersonalAbility;
    currentStats: Stats;
    totalGrowthRate: GrowthRate;
    equippedWeapon: Equipment;
    equippedAbilities: Ability[];
    currentClass: UnitClass;
    exp: number;
    level: number;
    unitTypes: string[];
    gold: number;
    attack: number;
    heal: number;
    damage: number;
    crit: number;
    avoid: number;
    dodge: number;
    damageReceived: number;
    attackSpeed: number;
    dualStrike: number;
    dualGuard: number;
    startingClass: string;
    heartSealClass: string;
    internalLevel: number;
    isInCombat: boolean;
    isAttacking: boolean;
    isWeaponTriangleAdvantage: boolean;
    isWeaponTriangleDisadvantage: boolean;
    dealsEffectiveDamage: boolean;
    effectiveDamageTypes: string[];
    asset: Asset;
    flaw: Flaw;
    condition: Condition;
    terrain: Terrain;
    inventory: Inventory;
    baseStats: Stats;
    statChangeAmount: Stats;
    maxStats: Stats;
    personalGrowthRate: GrowthRate;
    reclassOptions: string[];
    weaponRanks: Weapon[];
    supports?: Support[];
    acquiredAbilities: Ability[];
    skills: Skill[];
    levelUpStatIncreases?: LevelUp;
    convoyId: string;
}