using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Fire_Emblem.Common.TypeCodes
{
    public enum ClassType
    {
        Apothecary,
        Archer,
        Assassin,
        Ballistician,
        Basara,
        Berserker,
        Blacksmith,
        BowKnight,
        Cavalier,
        Cleric,
        DarkFlier,
        DarkKnight,
        DarkMage,
        DawnNoble,
        DreadFighter,
        DuskNoble,
        FalconKnight,
        Fighter,
        General,
        Grandmaster,
        GreatKnight,
        GreatLord,
        GreatMaster,
        GriffonRider,
        Hero,
        KinshiKnight,
        Kitsune,
        Knight,
        Lodestar,
        Lord,
        Mage,
        Maid,
        MaligKnight,
        Manakete,
        ManaketeHeir,
        MasterNinja,
        MasterOfArms,
        Mechanist,
        Mercenary,
        Merchant,
        Myrmidon,
        NineTails,
        Ninja,
        OniChieftain,
        OniSavage,
        Paladin,
        PegasusKnight,
        Performer,
        Sage,
        Sniper,
        Sorcerer,
        SpearFighter,
        SpearMaster,
        Strategist,
        Swordmaster,
        Tactician,
        Taguel,
        Thief,
        Trickster,
        Troubadour,
        Vanguard,
        Villager,
        WarCleric,
        Warrior,
        Witch,
        Wolfskin,
        Wolfssegner,
        WyvernLord
    }
}
